stages:
  - build
  - test
  - coverage
  - deploy

.only-branches:
  only:
    refs:
      - master
      - schedules
      - devops
      - merge_requests

#-----------  Job Informations----------
# Type:       Build: release/debug
# OS:         windows
# Compiler:   vs2017

windows:build:
  extends:
    - .only-branches
  stage: build
  script:
    - ./ci/windows-prepare.bat
    - ./ci/windows-build.bat
  tags:
     - windows
     - deepranalytics
  artifacts:
    paths:
        - build/
  cache:
    paths:
        - build/

windows:test:
  extends:
    - .only-branches
  stage: test
  script:
    - ./ci/windows-test.bat
  needs: ["windows:build"]
  when: on_success

windows:coverage:
  extends:
    - .only-branches
  stage: coverage
  script:
    - ./ci/windows-coverage.bat
  needs: ["windows:test"]
  when: on_success
  artifacts:
    paths:
        - cppreport/
  cache:
    paths:
      - cppreport/

windows:deploy:
  extends:
    - .only-branches
  stage: deploy
  script: 
    - ./ci/windows-build.bat
  needs: ["windows:coverage"]
  when: on_success

#-----------  Job Informations----------
# Type:       Build: release/debug
# OS:         Linux
# Compiler:   gcc

linux:build:
  extends:
    - .only-branches
  stage: build
  script:
    - chmod +x "ci/linux-prepare.sh"
    - chmod +x "ci/linux-build.sh"
    - "ci/linux-prepare.sh"
    - "ci/linux-build.sh"
  tags:
     - linux
     - deepranalytics
  artifacts:
    paths:
        - build/
  cache:
    paths:
        - build/
  when: on_success
        
linux:test:
  extends:
    - .only-branches
  stage: test
  script: 
    - chmod +x "ci/linux-test.sh"
    - "ci/linux-test.sh"
  when: on_success
  needs: ["linux:build"]

linux:deploy:
  extends:
    - .only-branches
  stage: deploy
  script:
    - chmod +x "ci/linux-deploy.sh"
    - "ci/linux-deploy.sh"
  when: on_success
  needs: ["linux:test"]



  # deploy coverage report

pages:
  extends:
    - .only-branches
  stage: deploy
  script:
  - mkdir .public
  - cp -r cppreport/* .public
  - mv .public public
  artifacts:
    paths:
    - public
