stages:
  - build
  - test
  - deploy

#-----------  Job Informations----------
# Type:       Build: release/debug
# OS:         windows
# Compiler:   vs2017

windows:build:
  stage: build
  script:
    - "ci\\windows-prepare.bat"
    - "ci\\windows-build.bat"
  tags:
     - windows
     - shared
  artifacts:
    paths:
        - build/
  cache:
    paths:
        - build/

windows:test:
  stage: test
  script: "ci\\windows-test.bat"
  tags:
    - windows
    - shared

windows:deploy:
  stage: deploy
  script: 
    - "ci\\windows-build.bat"
  tags:
     - windows
     - shared



#-----------  Job Informations----------
# Type:       Build: release/debug
# OS:         Linux
# Compiler:   gcc

linux:build:
  stage: build
  script:
    - chmod +x "ci/linux-prepare.sh"
    - chmod +x "ci/linux-build.sh"
    - "ci/linux-prepare.sh"
    - "ci/linux-build.sh"
  tags:
     - linux
     - shared
  artifacts:
    paths:
        - build/
  cache:
    paths:
        - build/
        
linux:test:
  stage: test
  script: 
    - chmod +x "ci/linux-test.sh"
    - "ci/linux-test.sh"
  tags:
     - linux
     - shared

linux:deploy:
  stage: deploy
  script:
    - chmod +x "ci/linux-deploy.sh"
    - "ci/linux-deploy.sh"
  tags:
     - linux
     - shared
