stages:
  - build
  - test
  - deploy

build-windows:
  stage: build
  script:
    - "ci\\windows-prepare.bat"
    - "ci\\windows-build.bat"
  tags:
     - windows
     - shared

test-windows:
  stage: test
  script: "ci\\windows-test.bat"
  tags:
    - windows
    - shared

deploy-windows:
  stage: deploy
  script: "ci\\windows-deploy.bat"
  tags:
     - windows
     - shared

build-linux:
  stage: build
  script:
    - chmod +x "ci/linux-prepare.sh"
    - chmod +x "ci/linux-build.sh"
    - "ci/linux-prepare.sh"
    - "ci/linux-build.sh"
  tags:
     - linux
     - shared

test-linux:
  stage: test
  script: 
    - chmod +x "ci/linux-test.sh"
    - "ci/linux-test.sh"
  tags:
     - linux
     - shared

deploy-linux:
  stage: deploy
  script:
    - chmod +x "ci/linux-deploy.sh"
    - "ci/linux-deploy.sh"
  tags:
     - linux
     - shared
