stages:
  - build
  - test
  - coverage
  - deploy



# Code Quality Widget
include:
  - template: Code-Quality.gitlab-ci.yml

code_quality:
  stage: build
  image: docker:stable
  allow_failure: true
  services:
    - docker:stable-dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker info
    - docker run 
       --env CODECLIMATE_DEBUG=1 
       --env CODECLIMATE_CODE="$PWD" 
       --volume "$PWD":/code 
       --volume /var/run/docker.sock:/var/run/docker.sock 
       --volume /tmp/cc:/tmp/cc 
       codeclimate/codeclimate:0.85.2 analyze -f html > report.html

  tags:
    - linux
    - deepranalytics

#before_script:
#  - docker info

#build_image:
#  script:
#    - docker build -t my-docker-image .
#    - docker run my-docker-image /script/to/run/tests
    
.only-branches:
  only:
    refs:
      - master
      - schedules
      - devops
      - merge_requests 

#some comment 2
#-----------  Job Informations----------
# Type:       Build: release/debug
# OS:         windows
# Compiler:   vs2017

windows:build:
  extends:
    - .only-branches
  stage: build
  script:
    - ./ci/windows-prepare.bat
    - ./ci/windows-build.bat
  tags:
     - windows
     - deepranalytics
  artifacts:
    paths:
        - build/
  cache:
    paths:
        - build/

windows:test:
  extends:
    - .only-branches
  stage: test
  script:
    - ./ci/windows-test.bat
  needs: ["windows:build"]
  when: on_success

windows:coverage:
  extends:
    - .only-branches
  stage: coverage
  script:
    - ./ci/windows-coverage.bat
  needs: ["windows:test"]
  when: on_success
  artifacts:
    paths:
        - cppreport/
  cache:
    paths:
      - cppreport/

windows:deploy:
  extends:
    - .only-branches
  stage: deploy
  script: 
    - ./ci/windows-build.bat
  needs: ["windows:coverage"]
  when: on_success

#-----------  Job Informations----------
# Type:       Build: release/debug
# OS:         Linux
# Compiler:   gcc

linux:build:
  extends:
    - .only-branches
  stage: build
  script:
    - chmod +x "ci/linux-prepare.sh"
    - chmod +x "ci/linux-build.sh"
    - "ci/linux-prepare.sh"
    - "ci/linux-build.sh"
  tags:
     - linux
     - deepranalytics
  artifacts:
    paths:
        - build/
  cache:
    paths:
        - build/
  when: on_success
        
linux:test:
  extends:
    - .only-branches
  stage: test
  script: 
    - chmod +x "ci/linux-test.sh"
    - "ci/linux-test.sh"
  when: on_success
  needs: ["linux:build"]

linux:coverage:
  extends:
    - .only-branches
  stage: coverage
  script:
    - echo ""
  needs: ["linux:test"]

linux:deploy:
  extends:
    - .only-branches
  stage: deploy
  script:
    - chmod +x "ci/linux-deploy.sh"
    - "ci/linux-deploy.sh"
  when: on_success
  needs: ["linux:test"]



  # deploy coverage report

pages:
  extends:
    - .only-branches
  stage: deploy
  script:
  - mkdir .public
  - cp -r cppreport/* .public
  - mv .public public
  artifacts:
    paths:
    - public
