stages:
  - build
  - test
  - deploy

windows:build:
  stage: build
  script:
    - "ci\\windows-prepare.bat"
    - "ci\\windows-build.bat"
  tags:
     - windows
     - shared

windows:test:
  stage: test
  script: "ci\\windows-test.bat"
  tags:
    - windows
    - shared

windows:deploy:
  stage: deploy
  script: 
    - "ci\\windows-build.bat"
  tags:
     - windows
     - shared

linux:build:
  stage: build
  script:
    - chmod +x "ci/linux-prepare.sh"
    - chmod +x "ci/linux-build.sh"
    - "ci/linux-prepare.sh"
    - "ci/linux-build.sh"
  tags:
     - linux
     - shared

linux:test:
  stage: test
  script: 
    - chmod +x "ci/linux-test.sh"
    - "ci/linux-test.sh"
  tags:
     - linux
     - shared

linux:deploy:
  stage: deploy
  script:
    - chmod +x "ci/linux-deploy.sh"
    - "ci/linux-deploy.sh"
  tags:
     - linux
     - shared
