stages:
  - build
  - test
  - deploy

build-windows:
  stage: build
  script:
    - "ci\\windows-prepare.bat"
    - "ci\\windows-build.bat"


test-windows:
  stage: test
  script: "ci\\windows-test.bat"
  
deploy-windows:
  stage: deploy
  script: "ci\\windows-deploy.bat"
