stages:
  - build
  - test
  - deploy

#-----------  Job Informations----------
# Type:       Build: release/debug
# OS:         windows
# Compiler:   vs2017

windows:build:
  stage: build
  script:
    - ./ci/windows-prepare.bat
    - ./ci/windows-build.bat
  only:
    refs:
      - master
      - schedules
      - devops
  tags:
     - windows
     - deepranalytics
  artifacts:
    paths:
        - build/
  cache:
    paths:
        - build/

windows:test:
  stage: test
  script:
    - ./ci/windows-test.bat
  when: on_success

windows:deploy:
  stage: deploy
  script: 
    - ./ci/windows-build.bat
  when: on_success


#-----------  Job Informations----------
# Type:       Build: release/debug
# OS:         Linux
# Compiler:   gcc

linux:build:
  stage: build
  script:
    - chmod +x "ci/linux-prepare.sh"
    - chmod +x "ci/linux-build.sh"
    - "ci/linux-prepare.sh"
    - "ci/linux-build.sh"
  only:
    refs:
      - master
      - schedules
      - devops
  tags:
     - linux
     - deepranalytics
  artifacts:
    paths:
        - build/
  cache:
    paths:
        - build/
  when: on_success
        
linux:test:
  stage: test
  script: 
    - chmod +x "ci/linux-test.sh"
    - "ci/linux-test.sh"
  when: on_success

linux:deploy:
  stage: deploy
  script:
    - chmod +x "ci/linux-deploy.sh"
    - "ci/linux-deploy.sh"
  when: on_success
