
stages:
  - build
  - test
  - coverage
  - deploy

.only-branches:
  only:
    refs:
      - master
      - schedules
      - merge_requests

windows:build:
  extends:
    - .only-branches
  stage: build
  script:
    - ./ci/windows-prepare.bat
    - ./ci/windows-build.bat
  tags:
     - windows
     - deepranalytics
  artifacts:
    paths:
        - build/
    expire_in: 1 day


windows:test:
  extends:
    - .only-branches
  stage: test
  script:
    - ./ci/windows-test.bat
  needs: ["windows:build"]
  tags:
     - windows
     - deepranalytics

windows:coverage:
  extends:
    - .only-branches
  stage: coverage
  script:
    - ./ci/windows-coverage.bat
  needs: ["windows:test"]
  artifacts:
    paths:
        - cppreport/
  cache:
    paths:
      - cppreport/
  tags:
     - windows
     - deepranalytics

windows:deploy:
  extends:
    - .only-branches
  stage: deploy
  script: 
    - ./ci/windows-build.bat
  needs: ["windows:coverage", "windows:build"]
  tags:
     - windows
     - deepranalytics
