name: C/C++ CI

on: [push]

jobs:
  build-ubuntu:

    runs-on: [self-hosted, Linux, X64, deepr]
#     container:
#        image: deepr/devopsubuntu:latest
#        credentials:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}         

    steps:
      - uses: actions/checkout@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.pkg.github.com
          image: deepr/devopsubuntu:latest
          run: echo "hello world"
      
      - name: configure
        run: gcc --version
             
      - name: build
        run: | 
          echo "Build"
          whoami
          chmod +x "./ci/linux-build.sh"
          "./ci/linux-build.sh" 

      - name: test
        run: echo "Test"

  build-windows:
    runs-on: [self-hosted, Windows, X64, deepr]

    steps:
    - uses: actions/checkout@v1
      with:
        token: ${{ secrets.REPO_SCOPED_TOKEN }}
    - name: configure
      run: echo "Configure complete"
    - name: build
      run: ./ci/windows-build.bat
    - name: test
      run: echo "Test Complete"
