name: C/C++ CI

on: [push]

jobs:
#   build-ubuntu:

#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v1
#     - name: configure
#       run: mkdir -p build && cd build && cmake -DCMAKE_CXX_FLAGS="-Werror" ..
#     - name: build
#       run: cmake --build build
#     - name: test
#       run: cd build && ctest

  build-windows:
    runs-on: [self-hosted, Windows, X64, deepr]


    steps:
    - uses: actions/checkout@v1
      with:
        token: ${{ secrets.REPO_SCOPED_TOKEN }}
    - name: configure
      run: echo "Configure complete"
    - name: build
      run: ./ci/windows-build.bat
    - name: test
      run: echo "Test Complete"
