name: C/C++ CI

on: [push]

jobs:
  build-ubuntu:

    runs-on: [self-hosted, Linux, X64, deepr]
    container:
       image: deepr/devopsubuntu:latest
       credentials:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}         
#        env:
#            DOCKERHUB_USER: ${{ secrets.DOCKER_USERNAME }}
#            DOCKERHUB_PASS: ${{ secrets.DOCKER_PASSWORD }}
#            DOCKERHUB_EMAIL: manoj.kumar@deepranalytics.com
    steps:
#     - uses: docker://deepr/devopsubuntu:latest
#       with:
#         registry: index.docker.io
#         username: ${{ secrets.DOCKER_USERNAME }}
#         password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: configure
      run: gcc --version
    - name: build
      run: echo "Build"
    - name: test
      run: echo "Test"

  build-windows:
    runs-on: [self-hosted, Windows, X64, deepr]


    steps:
    - uses: actions/checkout@v1
      with:
        token: ${{ secrets.REPO_SCOPED_TOKEN }}
    - name: configure
      run: echo "Configure complete"
    - name: build
      run: ./ci/windows-build.bat
    - name: test
      run: echo "Test Complete"
